import type { InterviewBrief } from "@/lib/db/types";

/** Read-only interview brief. Shared by the result page and the Interviews page. */
export function BriefView({ brief, model }: { brief: InterviewBrief; model?: string }) {
  return (
    <div className="space-y-5 text-sm">
      <p className="leading-relaxed">{brief.summary}</p>
      <div className="grid gap-5 md:grid-cols-2">
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wide text-muted">Strengths</h4>
          <ul className="mt-2 space-y-2">
            {brief.strengths.map((s, i) => (
              <li key={i}>
                <span className="font-mono text-xs text-accent">{s.criterion}</span> {s.point}
                <span className="mt-0.5 block border-l-2 border-line pl-2 text-[13px] italic text-muted">“{s.evidence}”</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wide text-muted">Risks to test</h4>
          <ul className="mt-2 space-y-2">
            {brief.risks.map((r, i) => <li key={i}><span className="font-mono text-xs text-accent">{r.criterion}</span> {r.point}</li>)}
          </ul>
          {brief.logistics.length > 0 && (
            <>
              <h4 className="mt-4 text-xs font-semibold uppercase tracking-wide text-muted">Logistics</h4>
              <ul className="mt-2 list-disc space-y-1 pl-5">{brief.logistics.map((l) => <li key={l}>{l}</li>)}</ul>
            </>
          )}
        </div>
      </div>
      <div className="overflow-x-auto rounded-lg border border-line">
        <table className="data">
          <caption className="sr-only">Interview questions</caption>
          <thead><tr><th scope="col">#</th><th scope="col">Criterion</th><th scope="col">Question</th><th scope="col">Listen for</th></tr></thead>
          <tbody>
            {brief.questions.map((q, i) => (
              <tr key={i}>
                <td className="tabular-nums">{i + 1}</td><td className="font-mono">{q.criterion}</td>
                <td className="min-w-64">{q.question}</td><td className="min-w-56 text-muted">{q.listen_for}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {model && <p className="text-xs text-muted">Generated by {model} from the redacted CV and the rubric result. Scores come from code, not from this brief.</p>}
    </div>
  );
}
