// Copies the extraction system prompt and EXTRACTION_SCHEMA verbatim out of rubrics/KARGO_RUBRICS.md §3
// into lib/ai/rubricsPrompt.generated.ts, so the app never reads markdown at runtime.
// Usage: npx tsx scripts/gen-prompt.ts    (tests/unit/ai.test.ts fails if the generated file is stale)
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export function extractFromRubrics(md: string): { system: string; schema: string } {
  const sec = md.split("## 3. Extraction prompt")[1]?.split("\n## 4.")[0];
  if (!sec) throw new Error("KARGO_RUBRICS.md: section 3 not found");
  const system = sec.match(/\*\*System:\*\*\s*```\n([\s\S]*?)\n```/)?.[1];
  const schema = sec.match(/\*\*EXTRACTION_SCHEMA\*\*[^\n]*\n\s*```json\n([\s\S]*?)\n```/)?.[1];
  if (!system || !schema) throw new Error("KARGO_RUBRICS.md: system prompt or EXTRACTION_SCHEMA block not found");
  return { system, schema };
}

export function renderGenerated(md: string): string {
  const { system, schema } = extractFromRubrics(md);
  return `// GENERATED by scripts/gen-prompt.ts from rubrics/KARGO_RUBRICS.md section 3. Do not edit by hand.
export const EXTRACTION_SYSTEM_PROMPT = ${JSON.stringify(system)};

export const EXTRACTION_SCHEMA_TEXT = ${JSON.stringify(schema)};
`;
}

if (process.argv[1]?.endsWith("gen-prompt.ts")) {
  const root = process.cwd();
  const md = readFileSync(path.join(root, "rubrics/KARGO_RUBRICS.md"), "utf8");
  writeFileSync(path.join(root, "lib/ai/rubricsPrompt.generated.ts"), renderGenerated(md));
  console.log("wrote lib/ai/rubricsPrompt.generated.ts");
}
